language: node_js
script:
  - npm install lcov-server
  - npm run lint
  - npm test
  - npm run coverage
  - cat coverage/lcov.info | lcov-server --upload https://node-coverage-server.herokuapp.com
node_js:
  - "8"
